apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ubuntu-mgmt
spec:
  config: '{
    "cniVersion": "0.4.0",
    "plugins": [{
      "type": "macvlan",
      "master": "enp11s0",
      "mode": "bridge",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "host-local",
        "ranges": [
          [{ "subnet": "10.10.50.0/24", "rangeStart": "10.10.50.100", "rangeEnd": "10.10.50.110", "gateway": "10.10.50.1"}]
        ],
        "routes": [{ "dst": "0.0.0.0/0"}]
        }
    },
    {
      "type": "tuning",
      "promisc": true,
      "capbilities": { "mac": true }
    }]
  }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ubuntu-data
spec:
  config: '{
    "cniVersion": "0.4.0",
    "plugins": [{
      "type": "macvlan",
      "master": "enp11s0",
      "mode": "bridge",
      "capabilities": { "ips": true },
      "ipam": {
        "type": "host-local",
        "ranges": [
          [{ "subnet": "10.20.50.0/24", "rangeStart": "10.20.50.100", "rangeEnd": "10.20.50.110"}]
        ]
      }
    },
    {
      "type": "tuning",
      "promisc": true,
      "capbilities": { "mac": true }
    }]
  }'
