apiVersion: v1
kind: ConfigMap
metadata:
  name: macvtap-macpro-enp11s0
  namespace: default
  labels:
    app.kubernetes.io/component: network
    app.kubernetes.io/managed-by: cnao-operator
    networkaddonsoperator.network.kubevirt.io/version: 0.85.0
    prometheus.cnao.io: "true"
data:
  DP_MACVTAP_CONF: |
    [
      {
        "name"      : "mgmt",
        "master"    : "enp11s0",
        "mode"      : "bridge",
        "capacity"  : "20"
      }
    ]
