apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: kvtest
spec:
  nodeSelector:
    kubernetes.io/hostname: macpro
  domain:
    cpu:
      model: IvyBridge-IBRS
    machine:
      type: q35
    resources:
      requests:
        memory: "2048Mi"
        cpu: "1"
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
      - name: podinfo
        disk:
          bus: virtio
      - name: civars
        disk:
          bus: virtio
      interfaces:
      - name: mgmt
        macvtap: {}
        macAddress: 40:83:83:83:83:01
      - name: data
        macvtap: {}
        macAddress: 40:83:83:83:83:02
      - name: pod
        bridge: {}
  networks:
  - name: mgmt
    multus:
      networkName: macvtap-macpro
  - name: data
    multus:
      networkName: macvtap-macpro
  - name: pod
    pod: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: k83:5000/kvtest:3
  - name: cloudinitdisk
    cloudInitConfigDrive:
      secretRef:
        name: ubuntu-userdata
  - name: podinfo
    downwardAPI:
      fields:
      - path: annotations
        fieldRef:
          fieldPath: metadata.annotations
  - name: civars
    configMap:
      name: kvtest
