apiVersion: v1
kind: ConfigMap
metadata:
  name: macvtap-macpro-enp12s0
data:
  DP_MACVTAP_CONF: |
    [
      {
        "name"      : "dataplane",
        "master"    : "enp12s0",
        "mode"      : "bridge",
        "capacity"  : "20"
      }
    ]
