apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: bigip-kv
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ {"name": "bigip-mgmt"} ]'
  labels:
    app: bigip
spec:
  nodeSelector:
    kubernetes.io/hostname: macpro
  domain:
    cpu:
      model: IvyBridge-IBRS
    machine:
      type: q35
    resources:
      requests:
        memory: "4096Mi"
        cpu: "2"
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
      - name: podinfo
        disk:
          bus: virtio
      - name: networks
        disk:
          bus: virtio
      interfaces:
      - name: mgmt
        bridge: {}
      - name: data1
        bridge: {}
        macAddress: 40:00:00:00:00:02
      - name: data2
        bridge: {}
        macAddress: 40:00:00:00:00:03
      - name: data3
        bridge: {}
        macAddress: 40:00:00:00:00:01
  volumes:
  - name: containerdisk
    containerDisk:
      image: k83:5000/bigip-kv:base
  - name: cloudinitdisk
    cloudInitConfigDrive:
      secretRef:
        name: userdata
  - name: podinfo
    downwardAPI:
      fields:
      - path: annotations
        fieldRef:
          fieldPath: metadata.annotations
  - name: networks
    configMap:
      name: bigip-kv
  networks:
  - name: mgmt
    multus:
      networkName: mgmt
  - name: data1
    multus:
      networkName: data10
  - name: data2
    multus:
      networkName: data20
  - name: data3
    multus:
      networkName: data30
